[package]
name = "anya-core-metrics"
version.workspace = true
edition.workspace = true
description = "Metrics implementation for Anya Core"
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# Internal dependencies
anya-core-lib = { path = "../core" }

# Metrics
prometheus = { version = "0.13.3", features = ["process"] }
metrics = "0.21.1"
metrics-exporter-prometheus = "0.12.1"

# Use workspace dependencies 
tokio.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
thiserror.workspace = true
