repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  has_wiki: false
  has_projects: true
  has_downloads: false
  default_branch: main

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: ["continuous-integration/github-actions"]
      enforce_admins: true
      restrictions: null
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

  - name: "feature/*"
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
      enforce_admins: false
      restrictions: null
