[package]
name = "anya-bitcoin"
version.workspace = true
edition = "2021"
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
# Workspace inheritance
secp256k1.workspace = true
bitcoin.workspace = true
bitcoincore-rpc.workspace = true
tokio.workspace = true
serde.workspace = true
secp256k1-zkp = { version = "0.11.0", optional = true }
jsi = { version = "0.10", optional = true }

[lib]
name = "anya_bitcoin"
path = "src/lib.rs"

[features]
default = ["mobile"]
mobile = ["dep:jsi"]
advanced = []

