name = "anya-bitcoin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
# Workspace inheritance
secp256k1.workspace = true
bitcoin.workspace = true
bitcoincore-rpc.workspace = true
tokio.workspace = true
serde.workspace = true

[lib]
name = "anya_bitcoin"
path = "src/lib.rs"

[features]
default = ["mobile"]
mobile = [
    "bitcoin/mobile", 
    "secp256k1/mobile",
    "secp256k1-zkp/mobile",
    "jsi"
]
advanced = ["bip340", "bip341", "bip342"]
