[package]
name = "anya-bitcoin"
version = "0.1.0"
edition = "2021"
description = "Bitcoin implementation following hexagonal architecture principles"
authors = ["bo_thebig <botshelomokokoka@gmail.com>"]
license = "MIT"

[dependencies]
async-trait = { workspace = true }
bitcoin = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.94"
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
secp256k1 = { workspace = true }
chrono = "0.4.31"
uuid = { version = "1.6.1", features = ["v4", "serde"] }
rand = "0.8.5"

[dev-dependencies]
mockall = "0.11.3"
tempfile = "3.5.0"
test-log = "0.2.11"

[lib]
name = "anya_bitcoin"
path = "src/lib.rs" 