[package]
name = "anya"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
anya-core = { path = "dependencies/anya-core" }
anya-enterprise = { path = "dependencies/anya-enterprise" }
anya-bitcoin = { path = "dependencies/anya-bitcoin" }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
uuid = { version = "1.0", features = ["v4"] }
async-trait = "0.1"
thiserror = "2.0.3"
log = "0.4"
env_logger = "0.11.5"
futures = "0.3"

[[bin]]
name = "run_fixes"
path = "scripts/run_fixes.rs"

[[bin]]
name = "run_progress"
path = "scripts/run_progress.rs"

[[bin]]
name = "run_alignment"
path = "scripts/run_alignment.rs"

[workspace]
members = [
    "scripts",
    "dependencies/anya-core",
    "dependencies/anya-enterprise",
    "dependencies/anya-bitcoin"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Anya Core Contributors"]
license = "MIT"
repository = "https://github.com/anya-ai/anya"
description = "Enterprise-grade Bitcoin wallet and transaction management system"
