[workspace]
members = [
    "core",
    "cli"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Anya Development Team"]
description = "Bitcoin Layer 4 Protocol Implementation"
license = "Apache-2.0"
repository = "https://github.com/anya-im/anya-core"

[workspace.dependencies]
bitcoin = { version = "0.29.2", features = ["rand", "serde"] }
secp256k1 = { version = "0.24.0", features = ["rand", "serde"] }
tokio = { version = "1.28.1", features = ["full"] }
serde = { version = "1.0.160", features = ["derive"] }
