# Anya Core Workspace - Centralized Dependency Management
# Enforces LTS (Long-Term Support) versions across all crates

[workspace]
resolver = "2"
members = [
    ".",
    "anya-bitcoin",
    "anya-core", 
    "anya-enterprise",
    "anya-extensions",
    "anya-web5-service",
    "bitcoin-adapter",
    "cli",
    "core",
    "dlc-oracle",
    "scripts",
    "servers",
    "src/bitcoin/anya-bitcoin",
    "src/extensions/anya-extensions",
    "dependencies/anya-bitcoin",
    "dependencies/anya-enterprise", 
    "dependencies/anya-extensions",
]

[workspace.package]
version = "1.2.0"
edition = "2021"
rust-version = "1.63.0"
authors = ["botshelomokoka+anya-core@gmail.com"]
license = "MIT"
repository = "https://github.com/anya-org/anya-core"
description = "Enterprise-grade Bitcoin Infrastructure Platform"

[workspace.dependencies]
bitcoin = { version = "=0.32.6", features = ["std", "serde", "rand", "secp-recovery", "base64", "rand-std"] }
secp256k1 = { version = "=0.31.1", features = ["global-context", "recovery", "rand"] }
bitcoincore-rpc = { version = "=0.19.0", features = ["default"] }
bitcoin_hashes = { version = "=0.14.0", features = ["std", "serde"] }
miniscript = { version = "=12.3.0", features = ["std", "compiler"] }
bdk = { version = "=0.30.0", features = ["std", "key-value-db", "all-keys"] }
tokio = { version = "=1.45.1", features = ["full"] }
futures = { version = "=0.3.31" }
async-trait = { version = "=0.1.88" }
serde = { version = "=1.0.219", features = ["derive", "rc"] }
serde_json = { version = "=1.0.140", features = ["std", "preserve_order", "arbitrary_precision"] }
axum = { version = "=0.8.4" }
tower = { version = "=0.5.2" }
tower-http = { version = "=0.6.6", features = ["cors", "trace"] }
hyper = { version = "=1.6.0", features = ["full"] }
reqwest = { version = "=0.12.22", features = ["json"] }
anyhow = { version = "=1.0.98", features = ["std", "backtrace"] }
thiserror = { version = "=2.0.12" }
ring = { version = "=0.17.12", features = ["alloc"] }
sha2 = { version = "=0.10.8" }
hmac = { version = "=0.12.1" }
aes-gcm = { version = "=0.10.3" }
chacha20poly1305 = { version = "=0.10.1" }
uuid = { version = "=1.17.0", features = ["v4", "serde"] }
chrono = { version = "=0.4.34", features = ["serde"] }
rand = { version = "=0.8.5" }
rand_core = { version = "=0.6.4" }
rand_distr = { version = "=0.4.3" }
hex = { version = "=0.4.3" }
base64 = { version = "=0.22.1" }
log = { version = "=0.4.27" }
tracing = { version = "=0.1.41" }
tracing-subscriber = { version = "=0.3.19" }
libp2p = { version = "=0.56.0", features = ["kad", "mdns", "noise", "tcp", "websocket", "yamux"] }
web5 = { git = "https://github.com/TBD54566975/web5-rs", rev = "310d79c9" }
jsonwebtoken = { version = "=9.3.1", features = ["use_pem"] }
multibase = { version = "=0.9.1", features = ["std"] }
multihash = { version = "=0.19.3", features = ["std"] }
mockall = { version = "=0.13.1" }
tempfile = { version = "=3.20.0" }
tokio-test = { version = "=0.4.4" }
tower-test = { version = "=0.4.0" }
criterion = { version = "=0.6.0", features = ["html_reports", "async"] }
clap = { version = "=4.5.0", features = ["derive"] }
console = { version = "=0.15.8" }
indicatif = { version = "=0.17.8" }
config = { version = "=0.14.0" }
humantime-serde = { version = "=1.1.1" }
lightning = { version = "=0.0.118", features = ["std"] }
lightning-invoice = { version = "=0.29.0" }
ipfs-api-backend-hyper = { version = "=0.6.0", features = ["with-builder"] }
ipfs-embed = { version = "=0.26.1", default-features = true }
lru = { version = "=0.12.4" }
libc = { version = "=0.2.166" }
nix = { version = "=0.28.0" }
rayon = { version = "=1.10.0" }
dashmap = { version = "=6.1.0", features = ["serde"] }
once_cell = { version = "=1.21.3" }
lazy_static = { version = "=1.5.0" }
regex = { version = "=1.9.6" }
walkdir = { version = "=2.5.0" }
blake3 = { version = "=1.8.2" }
k256 = { version = "=0.13.4", features = ["std"] }
ecdsa = { version = "=0.16.9" }
elliptic-curve = { version = "=0.13.8" }
semver = { version = "=1.0.26" }
syn = { version = "=2.0.101", features = ["parsing", "full"] }
vergen = { version = "=8.3.1", features = ["build", "git", "gitcl"] }
hickory-resolver = { version = "=0.24.0" }
geiger = { version = "=0.5.0" }
clarinet-utils = { version = "=1.0.0" }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.test]
opt-level = 0
debug = 2
debug-assertions = true
overflow-checks = true

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
codegen-units = 1

[package]
name = "anya-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = [
    "bitcoin",
    "cryptocurrency", 
    "blockchain",
    "enterprise",
    "hexagonal",
]
categories = [
    "api-bindings",
    "cryptography::cryptocurrencies",
]

[features]
default = ["std", "rust-bitcoin"]
hsm = []
complete = []
std = []
bitcoin_integration = []
rust-bitcoin = ["bitcoin"]
rsk = []
system-alignment = [
    "bitcoin_integration",
    "hsm",
]
web5 = []
memory_tracking = []
chaos-viz = []
ffi = ["std"]
mobile = ["ffi", "std", "bitcoin/std", "bitcoin/rand-std", "secp256k1/global-context", "secp256k1/rand"]

[dependencies]
bitcoin = { workspace = true, optional = true }
secp256k1 = { workspace = true }
bitcoincore-rpc = { workspace = true }
bitcoin_hashes = { workspace = true }
miniscript = { workspace = true }
bdk = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
humantime-serde = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
hyper = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
ring = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
aes-gcm = { workspace = true }
chacha20poly1305 = { workspace = true }
blake3 = { workspace = true }
k256 = { workspace = true }
ecdsa = { workspace = true }
elliptic-curve = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
rand_distr = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
libp2p = { workspace = true }
web5 = { workspace = true }
jsonwebtoken = { workspace = true }
multibase = { workspace = true }
multihash = { workspace = true }
ipfs-api-backend-hyper = { workspace = true }
ipfs-embed = { workspace = true }
lru = { workspace = true }
rayon = { workspace = true }
dashmap = { workspace = true }
once_cell = { workspace = true }
lazy_static = { workspace = true }
regex = { workspace = true }
walkdir = { workspace = true }
hickory-resolver = { workspace = true }
libc = { workspace = true }
config = { workspace = true }
semver = { workspace = true }
syn = { workspace = true }
geiger = { workspace = true }
clarinet-utils = { workspace = true }
mockall = { workspace = true }
lightning = { workspace = true, features = ["std"] }
lightning-invoice = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
mockall = { workspace = true }
tempfile = { workspace = true }
tokio-test = { workspace = true }
tower-test = { workspace = true }
criterion = { workspace = true }
did-key = "0.2.1"

[lib]
name = "anya_core"
path = "src/lib.rs"

[[bin]]
name = "anya"
path = "src/main.rs"
