[package]
<<<<<<< HEAD
name = "anya-core"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
bitcoin = { version = "0.29", features = ["rand"] }
bitcoin_fee_estimation = "0.1"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
ndarray = "0.15"
ndarray-stats = "0.5"
linfa = "0.6"
linfa-linear = "0.6"
rand = "0.8"
web3 = "0.18"
substrate-api-client = "0.13"
cosmos-sdk = "0.1"

# ... (other dependencies)
>>>>>>> c9fe62bf07bc8e7e0a11b9b0e4e6375f56b5c4cc
>>>>>>> 279f5ad40ab979cd8a5acdbfee77325abc6ee5cf
