[package]
name = "anya-core"
version = "0.3.0-rc.1"
edition = "2021"
description = "Enterprise-grade Bitcoin Infrastructure Platform"
authors = ["botshelomokoka@gmail.com"]
license = "MIT"
repository = "https://github.com/anya-org/anya-core"

[features]
default = ["std", "rust-bitcoin"]
# Feature flag for HSM functionality
hsm = ["dep:sha2", "dep:hmac"]
# Feature flag for complete system (including HSM)
complete = ["hsm"]
std = []
# Bitcoin implementation features
bitcoin_integration = []
rust-bitcoin = ["bitcoin", "bdk"]
# RSK integration for Bitcoin verification
rsk = []

[dependencies]
# API dependencies
axum = "0.7.4"
tower = "0.4.13"
tower-http = { version = "0.5.0", features = ["cors", "trace"] }
hyper = { version = "1.1.0", features = ["full"] }
tokio = { version = "1.36.0", features = ["full"] }

# Bitcoin dependencies
bitcoin = { version = "0.32.0", features = ["std", "serde", "rand", "bitcoinconsensus"] }
secp256k1 = { version = "0.28.1", features = ["std", "serde", "rand"] }
bdk = "0.28.2"
miniscript = "11.0.0"

# Web5/DID dependencies 
web5 = { git = "https://github.com/TBD54566975/web5-rs" }
jsonwebtoken = "8.3.0"
multibase = "0.9.1"
multihash = "0.18.1"

# Serialization/Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"

# Error handling
anyhow = "1.0.78"
thiserror = "1.0.56"

# Logging
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# Utilities and common dependencies
async-trait = "0.1.77"
clap = { version = "4.4.7", features = ["derive"] }
base64 = "0.21.4"
uuid = { version = "1.6.1", features = ["v4", "serde"] }
chrono = { version = "0.4.31", features = ["serde"] }
rand = "0.8.5"
argon2 = "0.5.0"
hex = "0.4"
log = "0.4"
reqwest = { version = "0.11", features = ["json"] }

# Conditionally required dependencies (HSM feature)
sha2 = { version = "0.10.7", optional = true }
hmac = { version = "0.12.1", optional = true }

[dev-dependencies]
mockall = "0.12.1"
tokio-test = "0.4.3"
tower-test = "0.4.0"


