[workspace]
resolver = "2"
members = [
    "core",
    "anya-core",
    "cli"
]

# Explicitly exclude all other crates to avoid conflicts
exclude = [
    "anya-bitcoin",
    "anyacore",
    "anya-enterprise", 
    "anya-extensions",
    "anya-mobile",
    "bitcoin-adapter",
    "dependencies",
    "enterprise",
    "installer",
    "mobile",
    "scripts",
    "src",
    "workspace"
]
