[package]
name = "anya"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "anya-core",
    "anya-enterprise",
    "src",
]

[dependencies]
log = "0.4"
tokio = { version = "1", features = ["full"] }
actix-web = "4"
yew = { version = "0.18", features = ["csr"] }
# Add other dependencies as needed
serde = "1.0"
serde_json = "1.0"
web5 = { git = "https://github.com/TBD54566975/web5-rust", branch = "main" }
rust-dlc = { git = "https://github.com/p2pderivatives/rust-dlc", branch = "main" }
bitcoincore-rpc = "*"
bulletproofs = "*"
did-key = "*"
verifiable-credentials = "*"
slog = "*"
slog-term = "*"
gorules = { git = "https://github.com/gorules/gorules-rust", branch = "main" }
rust-lightning = "0.0.14"

[dev-dependencies]
criterion = "*"
tokio-test = "*"
mockall = "*"
proptest = "*"
tempfile = "*"

[build-dependencies]
neon-build = "*"

[features]
default = ["std"]
std = []
enterprise = ["advanced_analytics", "high_volume_trading"]
advanced_analytics = []
high_volume_trading = []

[[bench]]
name = "core_benchmarks"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]