[package]
name = "anya"
version.workspace = true
edition = "2024"
authors.workspace = true
license.workspace = true

[dependencies]
anya-enterprise = { path = "./enterprise" }
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
env_logger = "0.11.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
async-trait = "0.1"
thiserror = "2.0.3"
chrono = "0.4"

[[bin]]
name = "run_fixes"
path = "scripts/run_fixes.rs"

[[bin]]
name = "run_progress"
path = "scripts/run_progress.rs"

[[bin]]
name = "run_alignment"
path = "scripts/run_alignment.rs"

[workspace]
members = [
    "scripts",
]
