[package]
name = "anya-core"
version = "0.3.0-rc.2"
edition = "2021"
description = "Enterprise-grade Bitcoin Infrastructure Platform"
authors = ["botshelomokoka@gmail.com"]
license = "MIT"
repository = "https://github.com/anya-org/anya-core"

[features]
default = ["std", "rust-bitcoin"]
# Feature flag for HSM functionality
hsm = ["dep:sha2", "dep:hmac"]
# Feature flag for complete system (including HSM)
complete = ["hsm"]
std = []
# Bitcoin implementation features
bitcoin_integration = []
rust-bitcoin = ["bitcoin", "bdk"]
# RSK integration for Bitcoin verification
rsk = []

[dependencies]
# API dependencies
axum = "=0.8.4"
tower = "=0.5.2"
tower-http = { version = "=0.6.4", features = ["cors", "trace"] }
hyper = { version = "=1.6.0", features = ["full"] }
tokio = { version = "=1.45.1", features = ["full"] }

# Bitcoin dependencies
bitcoin = { version = "0.32", features = ["std", "serde", "rand", "bitcoinconsensus", "secp-recovery", "base64", "rand-std", "bitcoinconsensus-std"], optional = true }
secp256k1 = { version = "0.29", features = ["rand-std", "global-context"] }
bdk = { version = "0.30", optional = true }
miniscript = "12.3"
bip39 = "2.0"

# Web5/DID dependencies 
web5 = { git = "https://github.com/TBD54566975/web5-rs", rev = "310d79c9" }
jsonwebtoken = "=9.3.1"
multibase = "=0.9.1"
multihash = "=0.19.3"

# Serialization/Deserialization
serde = { version = "=1.0.214", features = ["derive"] }
serde_json = "=1.0.133"
humantime-serde = "=1.1.1"
getrandom = "=0.3.3"
url = "=2.5.4"

# Error handling
anyhow = "=1.0.93"
thiserror = "=2.0.12"

# Logging
tracing = "=0.1.41"
tracing-subscriber = { version = "=0.3.18", features = ["env-filter"] }

# Utilities and common dependencies
async-trait = "=0.1.84"
clap = { version = "=4.5.39", features = ["derive"] }
base64 = "=0.22.1"
uuid = { version = "=1.11.0", features = ["v4", "serde"] }
chrono = { version = "=0.4.38", features = ["serde"] }
rand = "=0.8.5"
argon2 = "=0.5.3"
hex = "=0.4.3"
log = "=0.4.22"
reqwest = { version = "=0.12.9", features = ["json", "blocking"] }
clap_derive = "=4.5.32"
actix-web = "=4.11.0"
actix-cors = "=0.7.1"
env_logger = "=0.11.8"
jwt = "=0.16.0"
ring = "=0.17.8"
sysinfo = "=0.32.1"
dialoguer = "=0.11.0"
warp = "=0.3.7"
cargo_metadata = "=0.20.0"
maplit = "=1.0.2"
systemstat = "=0.2.3"
regex = "=1.11.1"
toml = "=0.8.19"
serde_yaml = "=0.9.34"
tokio-tungstenite = "=0.24.0"

# Conditionally required dependencies (HSM feature and general codebase)
sha2 = { version = "=0.10.8", optional = true }
hmac = { version = "=0.12.1", optional = true }
zeroize = "=1.8.1"
criterion = "0.6.0"
walkdir = "2.5.0"
once_cell = "1.21.3"
dashmap = "6.1.0"
rayon = "1.10.0"
blake3 = "1.8.2"
semver = "1.0.26"
syn = { version = "2.0.101", features = ["full"] }

[dev-dependencies]
mockall = "=0.13.1"
tokio-test = "=0.4.4"
tower-test = "=0.4.0"
