[package]
name = "anya-core"
version = "0.1.0"
edition = "2021"
<<<<<<< Updated upstream
authors = ["Anya Core Contributors"]
description = "A decentralized AI assistant framework (Open Source Edition)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/anya-core/anya-core"

[workspace]
members = [
    "anya-core",
    "anya-network",
    "anya-ai",
    "anya-cli"
]

[dependencies]
tokio = { version = "1.28", features = ["full"] }
slog = "2.7"
slog-term = "2.9"
config = "0.11"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libp2p = "0.51"
ipfs-api = "0.17"
yew = "0.20"
clap = { version = "4.3", features = ["derive"] }
bitcoin = "0.30"
bitcoincore-rpc = "0.16"
lightning = "0.0.116"
lightning-invoice = "0.24"
rust-dlc = "0.4"
clarity-repl = "1.0"
stacks-rpc-client = "1.0"
ndarray = "0.15"
chrono = "0.4"
ta = "0.5"
statrs = "0.16"
linfa = "0.6"
linfa-linear = "0.6"
ring = "0.16"
bitcoin = { version = "0.30", features = ["rand"] }

[dev-dependencies]
criterion = "0.5"
mockall = "0.11"
proptest = "1.0"

[[bench]]
name = "core_benchmarks"
harness = false
=======
authors = ["botshelomokoka@gmail.com"]
description = "Bitcoin-centric AI assistant framework"
license = "MIT OR Apache-2.0"

[dependencies]
# Blockchain
bitcoin = "0.29.2"
bitcoincore-rpc = "0.16.0"
lightning = "0.0.116"
stacks-core = "2.1.0"
rust-dlc = "0.4.1"

# Identity
did-key = "0.1"
verifiable-credentials = "0.1"
web5 = "0.1.0"

# Networking
libp2p = "0.51"

# Smart Contracts
clarity-repl = "1.0.1"
wasmer = "2.3"

# Federated Learning
openfl = "0.1"

# Privacy
bulletproofs = "4.0"

# UI
yew = "0.19"
clap = "3.2"

# Utility
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10.0"
thiserror = "1.0"

# New dependencies
reqwest = { version = "0.11", features = ["json"] }
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1.25", features = ["serde"] }

[dev-dependencies]
criterion = "0.4.0"
tokio-test = "0.4.2"
mockall = "0.11.3"
>>>>>>> Stashed changes

[features]
default = ["std"]
std = []
<<<<<<< Updated upstream

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
=======
enterprise = ["advanced_analytics", "high_volume_trading"]
advanced_analytics = []
high_volume_trading = []
>>>>>>> Stashed changes
