[package]
name = "anya-workspace"
version = "2.5.0"
edition = "2021"
authors = ["Anya Core Team"]
description = "Anya Core Bitcoin Development Framework"
repository = "https://github.com/anya-org/anya-core"
license = "MIT"

[workspace]
members = [
    "core",
    "bitcoin",
    "packages/core",
    "packages/bitcoin-network",
    "packages/metrics",
    "packages/protocol-adapters",
    "packages/mcp-interface",
    "packages/bin",
    "packages/privacy",
    "extensions/enterprise",
    "extensions/mobile"
]
resolver = "2"

[workspace.dependencies]
# Bitcoin dependencies
bitcoin = { version = "0.32.5", features = ["rand", "serde"] }
secp256k1 = { version = "0.28.0", features = ["bitcoin_hashes", "rand"] }
bitcoincore-rpc = "0.19.0"
bdk = { version = "0.30.2", default-features = false }

# Async runtime & networking
tokio = { version = "1.37.0", features = ["full", "tracing"] }
futures = "0.3.30"
libp2p = { version = "0.55.0", features = ["full"] }
tokio-signal = "0.2.9"
async-trait = "0.1.73"
tokio-util = "0.7.10"
tower = { version = "0.4.13", features = ["util", "timeout"] }
tower-http = { version = "0.4.4", features = ["trace", "cors", "compression-gzip"] }

# Other dependencies as in original file...
