[package]
name = "anya"
version = "0.1.0"
edition = "2021"
authors = ["botshelomokoka@gmail.com"]
description = "A Bitcoin, Taproot Asset and AI-enabled wallet with ZK capabilities, project setup, and setup checking"
license = "MIT"

[dependencies]
# Bitcoin and cryptocurrency related
bitcoin = { version = "*", features = ["latest"] }
bitcoincore-rpc = { version = "*", features = ["latest"] }
secp256k1 = { version = "*", features = ["latest"] }
rust-bitcoin = { version = "*", features = ["latest"] }
rust-lightning = { version = "*", features = ["latest"] }
rust-miniscript = { version = "*", features = ["latest"] }
rust-bip39 = { version = "*", features = ["latest"] }
rust-secp256k1 = { version = "*", features = ["latest"] }
rust-base58 = { version = "*", features = ["latest"] }
rust-bech32 = { version = "*", features = ["latest"] }

# Cryptography and hashing
sha2 = { version = "*", features = ["latest"] }
hex = { version = "*", features = ["latest"] }
bech32 = { version = "*", features = ["latest"] }
rust-crypto = { version = "*", features = ["latest"] }

# Serialization and deserialization
serde = { version = "*", features = ["derive", "latest"] }
serde_json = { version = "*", features = ["latest"] }

# Async runtime and networking
tokio = { version = "*", features = ["full", "latest"] }
reqwest = { version = "*", features = ["json", "latest"] }

# Error handling
thiserror = { version = "*", features = ["latest"] }

# Random number generation
rand = { version = "*", features = ["latest"] }

# Zero-Knowledge Proof Libraries
ark-ff = { version = "*", features = ["latest"] }
ark-ec = { version = "*", features = ["latest"] }
ark-bls12-381 = { version = "*", features = ["latest"] }
ark-groth16 = { version = "*", features = ["latest"] }
ark-serialize = { version = "*", features = ["latest"] }
ark-snark = { version = "*", features = ["latest"] }

# For ZK-friendly hash functions
blake2 = { version = "*", features = ["latest"] }

# For ZK-SNARKs
bellman = { version = "*", features = ["latest"] }
pairing = { version = "*", features = ["latest"] }

# For ZK-STARKs
winterfell = { version = "*", features = ["latest"] }

# Logging
log = { version = "*", features = ["latest"] }
slog = { version = "*", features = ["latest"] }
env_logger = { version = "*", features = ["latest"] }

# Environment variables
dotenv = { version = "*", features = ["latest"] }

# File system operations
fs_extra = { version = "*", features = ["latest"] }

# Networking (Kademlia)
kademlia = { version = "*", features = ["latest"] }  # Replace with actual Kademlia library if different

[dev-dependencies]
mockall = { version = "*", features = ["latest"] }
tokio-test = { version = "*", features = ["latest"] }
