[package]
name = "anya-core"
version = "0.1.0"
edition = "2021"
authors = ["Human <botshelomokoka@gmail.com>"]
description = "Core functionality for the Anya AI assistant"
license = "MIT"
repository = "https://github.com/botshelomokoka/anya-core-main"

[dependencies]
# Core dependencies
tokio = { version = "1.28", features = ["full"] }
async-trait = "0.1.68"
futures = "0.3.28"

# Logging and error handling
log = "0.4.17"
env_logger = "0.10.0"
thiserror = "1.0.40"
anyhow = "1.0.71"

# NLP and machine learning
rust-bert = "0.20.0"

# HTTP client
reqwest = { version = "0.11.18", features = ["json"] }

# Serialization and deserialization
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"

# Configuration management
config = "0.13.3"
dotenv = "0.15.0"

# CLI interface
clap = { version = "4.3.0", features = ["derive"] }

# Date and time utilities
chrono = "0.4.24"

[dev-dependencies]
tokio-test = "0.4.2"
mockall = "0.11.4"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true

[profile.test]
opt-level = 3
debug = true
