[package]
name = "anya-core"
version = "0.3.0"
edition = "2021"
authors = ["Anya Core Contributors"]
description = "Core functionality for Anya AI Assistant"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
bitcoin = "0.30"
bitcoin_fee_estimation = "0.1"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
ndarray = "0.15"
ndarray-stats = "0.5"
linfa = "0.6"
linfa-linear = "0.6"
rand = "0.8"
actix-web = "4.3"
utoipa = { version = "3.3", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "3.1", features = ["actix-web"] }
log = "0.4"
pyo3 = { version = "0.18", features = ["extension-module"] }
numpy = "0.18"
opendp = "0.6"
pyspdz = "0.1"
tenseal = "0.4"

[features]
default = []
enterprise = []
