[package]
name = "anya"
version = "0.2.0"
edition = "2021"
description = "Decentralized AI Governance System"
authors = ["Botshelo Mokoka <botshelomokoka@gmail.com>"]
license = "MIT"

[dependencies]
# Async Runtime
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# Error Handling
thiserror = "1.0"
anyhow = "1.0"
backtrace = "0.3"

# Async Traits
async-trait = "0.1"

# Web5 Integration
web5 = "0.1"
web5-credentials = "0.1"
web5-did = "0.1"
web5-protocol = "0.1"
web5-storage = "0.1"
jsonschema = "0.17"

# Blockchain Integration
clarity-sdk = { git = "https://github.com/stacks-network/clarity-sdk", rev = "latest" }
stacks-rpc-client = { git = "https://github.com/stacks-network/stacks-blockchain-api", rev = "latest" }

# Networking
libp2p = { version = "0.53", features = ["full"] }

# Logging and Metrics
tracing = { version = "0.1", features = ["attributes", "async-await"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-futures = "0.2"
metrics = "0.21"
metrics-exporter-prometheus = "0.12"

# Time and Date
chrono = "0.4"

# Utilities
uuid = { version = "1.0", features = ["v4"] }
lru = "0.10"
parking_lot = "0.12"
once_cell = "1.18"

# Configuration Management
config = "0.13"
lazy_static = "1.4"
dotenv = "0.15"

# Security
secrecy = "0.8"
ring = "0.17"  # Cryptographic operations
zeroize = { version = "1.6", features = ["zeroize_derive"] }  # Secure memory wiping
aes-gcm = "0.10"  # AES-GCM encryption
argon2 = "0.5"  # Password hashing
x509-parser = "0.15"  # Certificate handling
rustls = { version = "0.21", features = ["dangerous_configuration"] }  # TLS
data-encoding = "2.4"  # Encoding utilities

# Authentication
jsonwebtoken = "9.1"  # JWT handling
oauth2 = "4.4"  # OAuth2 support
totp-rs = "5.2"  # TOTP for 2FA

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.12"
proptest = "1.3"
test-log = { version = "0.2", features = ["trace"] }
tracing-test = "0.2"
criterion = "0.5"  # Benchmarking
cargo-audit = "0.18"  # Security auditing
cargo-deny = "0.13"  # Dependency checking

[[bin]]
name = "run_fixes"
path = "scripts/run_fixes.rs"

[[bin]]
name = "run_progress"
path = "scripts/run_progress.rs"

[[bin]]
name = "run_alignment"
path = "scripts/run_alignment.rs"

[workspace]
members = [
    "scripts",
    "dependencies/anya-core",
    "dependencies/anya-enterprise",
    "dependencies/anya-bitcoin"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Anya Core Contributors"]
license = "MIT"
repository = "https://github.com/botshelomokoka/anya-core"
description = "Enterprise-grade Bitcoin wallet and transaction management system"
