[package]
name = "anya"
version = "0.1.0"
edition = "2021"
description = "Decentralized AI Governance System"
authors = ["Botshelo Mokoka <botshelomokoka@gmail.com>"]
license = "MIT"

[dependencies]
# Async Runtime
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error Handling
thiserror = "1.0"
anyhow = "1.0"
backtrace = "0.3"

# Async Traits
async-trait = "0.1"

# Web5 Integration
web5 = "0.1"
web5-credentials = "0.1"
web5-did = "0.1"
web5-protocol = "0.1"
web5-storage = "0.1"
jsonschema = "0.17"

# Blockchain Integration
clarity-sdk = "0.1"
stacks-rpc-client = "0.1"

# Networking
libp2p = { version = "0.51", features = ["full"] }

# Logging and Metrics
tracing = { version = "0.1", features = ["attributes", "async-await"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-futures = "0.2"
metrics = "0.21"
metrics-exporter-prometheus = "0.12"

# Time and Date
chrono = "0.4"

# Utilities
uuid = { version = "1.0", features = ["v4"] }
lru = "0.10"
parking_lot = "0.12"
once_cell = "1.18"

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.12"
proptest = "1.3"
test-log = { version = "0.2", features = ["trace"] }
tracing-test = "0.2"

[[bin]]
name = "run_fixes"
path = "scripts/run_fixes.rs"

[[bin]]
name = "run_progress"
path = "scripts/run_progress.rs"

[[bin]]
name = "run_alignment"
path = "scripts/run_alignment.rs"

[workspace]
members = [
    "scripts",
    "dependencies/anya-core",
    "dependencies/anya-enterprise",
    "dependencies/anya-bitcoin"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Anya Core Contributors"]
license = "MIT"
repository = "https://github.com/anya-ai/anya"
description = "Enterprise-grade Bitcoin wallet and transaction management system"
