[package]
name = "anya"
version = "0.2.0"
edition = "2021"
description = "Decentralized AI Governance System"
authors = ["Botshelo Mokoka <botshelomokoka@gmail.com>"]
license = "MIT"

[dependencies]
# Async Runtime
tokio = { version = "1.32", features = ["full"] }
futures = "0.3.28"

# Serialization
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
serde_yaml = "0.9.25"

# Error Handling
thiserror = "1.0.47"
anyhow = "1.0.75"
backtrace = "0.3.69"

# Async Traits
async-trait = "0.1.73"

# Web5 Integration
web5 = "0.1"
web5-credentials = "0.1"
web5-did = "0.1"
web5-protocol = "0.1"
web5-storage = "0.1"
jsonschema = "0.17.1"

# Blockchain Integration
clarity-sdk = { git = "https://github.com/stacks-network/clarity-sdk", rev = "main" }
stacks-rpc-client = { git = "https://github.com/stacks-network/stacks-blockchain-api", rev = "main" }

# Networking
libp2p = { version = "0.53.1", features = ["full"] }

# Logging and Metrics
tracing = { version = "0.1.37", features = ["attributes", "async-await"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
tracing-futures = "0.2.5"
metrics = "0.21.1"
metrics-exporter-prometheus = "0.12.1"

# Time and Date
chrono = { version = "0.4.26", features = ["serde"], default-features = false }

# Utilities
uuid = { version = "1.0", features = ["v4"] }
lru = "0.10"
parking_lot = "0.12"
once_cell = "1.18"

# Configuration Management
config = "0.13"
lazy_static = "1.4"
dotenv = "0.15"

# Security
secrecy = "0.8"
ring = "0.17"  # Cryptographic operations
zeroize = { version = "1.6", features = ["zeroize_derive"] }  # Secure memory wiping
aes-gcm = "0.10"  # AES-GCM encryption
argon2 = "0.5"  # Password hashing
x509-parser = "0.15"  # Certificate handling
rustls = { version = "0.21", features = ["dangerous_configuration"] }  # TLS
data-encoding = "2.4"  # Encoding utilities

# Authentication
jsonwebtoken = "9.1"  # JWT handling
oauth2 = "4.4"  # OAuth2 support
totp-rs = "5.2"  # TOTP for 2FA

[dev-dependencies]
tokio-test = "0.4.3"
mockall = "0.11.4"
tempfile = "3.8.0"
criterion = "0.5.1"
proptest = "1.2.0"

[build-dependencies]
tonic-build = "0.10.1"

[features]
default = ["std"]
std = []
nightly = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = false
panic = "abort"

[profile.dev]
opt-level = 0
debug = true

[workspace]
members = [
    "crates/*"
]

[[bin]]
name = "run_fixes"
path = "scripts/run_fixes.rs"

[[bin]]
name = "run_progress"
path = "scripts/run_progress.rs"

[[bin]]
name = "run_alignment"
path = "scripts/run_alignment.rs"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Anya Core Contributors"]
license = "MIT"
repository = "https://github.com/botshelomokoka/anya-core"
description = "Enterprise-grade Bitcoin wallet and transaction management system"
