cargo-features = ["edition2024"]



[package]

name = "bitcoin_integration"

version = "0.1.0"

edition = "2021"



[workspace]

members = [

    "anya-core",
    # Add other members as needed
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["${CARGO_AUTHOR_NAME} <${CARGO_AUTHOR_EMAIL}>"]
repository = "${CARGO_REPOSITORY}"
license = "MIT OR Apache-2.0"



# Remove direct enterprise reference since it's a submodule

# and will be managed through git



[dependencies]

bitcoin = "0.30.1"

bitcoincore-rpc = "0.17.0"

tokio = { version = "1.32.0", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }

serde_json = "1.0"

thiserror = "1.0"

log = "0.4"

env_logger = "0.10"

anyhow = "1.0"

anya-core = { path = "./anya-core" }



[dev-dependencies]

tokio-test = "0.4"

assert_matches = "1.5"

criterion = "0.5"



[build-dependencies]

neon-build = "*"



[features]

default = ["std"]

std = []

# Enterprise features are now managed in the enterprise repo



[[bench]]

name = "enterprise_benchmarks"

path = "benches/enterprise_benchmarks/main.rs"

harness = false



[package.metadata.docs.rs]

all-features = true

rustdoc-args = ["--cfg", "docsrs"]




