[package]
name = "anya-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "Core functionality for Anya Bitcoin development"
build = "build.rs"

[dependencies]
# Logging
slog = "2.7"
slog-term = "2.9"
slog-async = "2.8"

# Bitcoin essentials
bitcoin = { version = "0.31.0", features = ["rand"] }
secp256k1 = { version = "0.27.0", features = ["rand"] }
bitcoincore-rpc = "0.17.0"

# Async runtime
tokio = { version = "1.34", features = ["full"] }

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Secure storage
secret-service = { version = "3.0", optional = true }
security-framework = { version = "2.9", optional = true }
winapi = { version = "0.3", features = ["wincred"], optional = true }
age = { version = "0.9", optional = true }
dirs = "5.0"

# Configuration
config = "0.13"

[dev-dependencies]
tokio-test = "0.4"

[features]
default = ["secure-storage"]
secure-storage = []
secure-storage-linux = ["secure-storage", "secret-service"]
secure-storage-macos = ["secure-storage", "security-framework"]
secure-storage-windows = ["secure-storage", "winapi"]
secure-storage-fallback = ["secure-storage", "age"]

[target.'cfg(target_os = "linux")'.dependencies]
secret-service = "3.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["wincred"] }

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.9"

[target.'cfg(not(any(target_os = "linux", target_os = "windows", target_os = "macos")))'.dependencies]
age = "0.9"
