cargo-features = ["edition2024"]



[package]

name = "anya"

version = "0.1.0"

edition = "2021"

authors = ["botshelomokoka <botshelomokoka@gmail.com>"]

repository = "https://github.com/botshelomokoka/anya"

license = "MIT OR Apache-2.0"  # Added this line



[workspace]

members = [
    "anya-core",
    # Add other members as needed
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["botshelomokoka <botshelomokoka@gmail.com>"]
repository = "https://github.com/botshelomokoka/anya"
license = "MIT OR Apache-2.0"  # Added this line



# Remove direct enterprise reference since it's a submodule

# and will be managed through git



[dependencies]

# Logging
slog = "2.7"
slog-term = "2.9"
slog-async = "2.8"

# Async
tokio = { version = "1.0", features = ["full"] }

# Error handling
anyhow = "1.0"

# Core functionality
anya-core = { path = "./anya-core" }

# Core Dependencies
serde = { version = "1.0", features = ["derive"] }

# ML Dependencies
tch = "0.13"
ndarray = "0.15"

# Web5 Dependencies (to be added)
did-key = "0.2"
dwn-sdk-rs = "0.1"




[dev-dependencies]

tokio-test = "0.4"

assert_matches = "1.5"

criterion = "0.5"



[build-dependencies]

neon-build = "*"



[features]

default = ["std"]

std = []

# Enterprise features are now managed in the enterprise repo



[[bench]]

name = "enterprise_benchmarks"

path = "benches/enterprise_benchmarks/main.rs"

harness = false



[package.metadata.docs.rs]

all-features = true

rustdoc-args = ["--cfg", "docsrs"]




