[package]
name = "anya-core"
version = "0.1.0"
edition = "2021"
authors = ["Anya Core Team"]
license = "MIT"
repository = "https://github.com/anya-org/anya"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
futures = "0.3.30"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_yaml = "0.9.25"
toml = "0.8.8"
anyhow = "1.0.75"
thiserror = "1.0"
async-trait = "0.1.77"
pyo3 = { version = "0.19.2", features = ["extension-module"] }
once_cell = "1.18.0"
regex = "1.9.5"
log = "0.4"
clap = { version = "4.4", features = ["derive"] }
systemstat = "4.0"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }

# Web5 Integration
web5 = { git = "https://github.com/TBD54566975/web5-rs", package = "web5", tag = "v4.0.0" }
jsonschema = "0.17.1"

# Blockchain Integration
bitcoin = { version = "0.32.1", features = ["rand", "rand-std"] }
bitcoincore-rpc = "0.17.0"
secp256k1 = "0.27.0"
bitcoin-wallet = "1.1.0"

# Networking
libp2p = { version = "0.53.1", features = ["full"] }

# Logging and Metrics
tracing = { version = "0.1.40", features = ["attributes", "async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
metrics = "0.21.1"

# Cryptography
ring = "0.17"
sha2 = "0.10.8"
ed25519-dalek = "2.1.1"
x25519-dalek = "2.0.0"
chacha20poly1305 = "0.10.1"
aes-gcm = "0.10.3"
hmac = "0.12.1"
pbkdf2 = "0.12.2"

# Testing
test = "0.15.4"
mockall = "0.11"
tokio-test = "0.4"

[target.'cfg(unix)'.dependencies]
std = { version = "1.0", features = ["os", "unix", "fs"] }

[target.'cfg(windows)'.dependencies]
std = { version = "1.0", features = ["os", "windows", "fs"] }

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.11"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true

[profile.dev]
opt-level = 0
debug = true

[[bin]]
name = "anya"
path = "src/main.rs"

[[bin]]
name = "api_server"
path = "src/bin/api_server.rs"

[[bin]]
name = "installer"
path = "src/bin/installer.rs"

[[bin]]
name = "lightning_demo"
path = "src/bin/lightning_demo.rs"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[[bin]]
name = "anya_validator"
path = "src/bin/anya_validator.rs"

[lib]
name = "anya"
path = "src/lib.rs"
