# Anya Core Workspace Configuration
[workspace]
members = [
    "packages/core",
    "packages/protocol-adapters",
    "packages/mcp-interface",
    "packages/bitcoin-network",
    "packages/metrics",
    "packages/bin",
    "extensions/enterprise",
    "extensions/mobile"
]
resolver = "2"

# Workspace package inheritance
[workspace.package]
version = "2.5.0"
edition = "2021"
description = "Anya Core Bitcoin Development Framework"
license = "MIT"
repository = "https://github.com/anya-org/anya-core"
rust-version = "1.70"

# Consolidated dependencies without duplicates
[workspace.dependencies]
# Unified cryptographic stack (BDF ยง1.1)
secp256k1 = { version = "0.27.0", features = ["bitcoin_hashes"] }
bitcoin = "0.30.0"
# taproot-assets dependency removed - repository not found

# Protocol Adapters (BDF ยง2.1)
bitcoin_hashes = "0.12.0"
bitcoin-bech32 = "0.13.0"
# Removed problematic features
bdk = { version = "0.30.0" }

# Shared Workspace Dependencies
tokio = { version = "1.37.0", features = [
    "full",
    "tracing"
] }
serde = { version = "1.0.203", features = ["derive"] }

# Error handling and randomness dependencies
thiserror = "1.0.65"
rand = "0.8.5"
rand_core = "0.6.4"

# Shared workspace dependencies
bitcoin-wallet = "1.1.0"

# Core dependencies
futures = "0.3.30"
serde_json = "1.0.133"
serde_yaml = "0.9.25"
toml = "0.8.8"
anyhow = { version = "1.0.79", features = ["backtrace"] }
# thiserror already defined above
async-trait = "0.1.77"
pyo3 = { version = "0.19.2", features = ["extension-module"] }
once_cell = "1.18.0"
regex = "1.9.5"
log = "0.4"
clap = { version = "4.5.4", features = ["derive"] }
systemstat = "4.0"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }

# Web5 Integration
jsonschema = "0.17.1"

# Blockchain Integration

# Networking
libp2p = { version = "0.53.1", features = ["full"] }

# Logging and Metrics
tracing = { version = "0.1.40", features = ["attributes", "async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
metrics = "0.21.1"

# Cryptography
ring = "0.17.12"
sha2 = "0.10.8"
ed25519-dalek = "2.1.1"
x25519-dalek = "2.0.0"
chacha20poly1305 = "0.10.1"
aes-gcm = "0.10.3"
hmac = "0.12.1"
pbkdf2 = "0.12.2"

# Testing
test = "0.15.4"
mockall = "0.11"
tokio-test = "0.4"

# Unified DLC implementation
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", tag = "v0.10.0", features = ["dlc-utils"] }

# Mobile dependencies
jsi = "0.10"

# [AIR-3] Remove Dart dependencies
# Note: Dependencies should be defined in workspace.dependencies or individual package manifests

# [BPC-3] Bitcoin Development Framework workspace
# Workspace is already defined at the top of the file

# These dependencies are already defined in the workspace.dependencies section above
# Note: taproot-assets is added to the main workspace.dependencies section

# [AIS-3] Security enforcement
# Note: rust-version is already specified in the workspace.package section at the top
