[package]
name = "anya-core"
version = "0.1.0"
edition = "2021"
authors = ["Anya Core Contributors"]
description = "A decentralized AI assistant framework (Open Source Edition)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/anya-core/anya-core"

[workspace]
members = [
    "anya-core",
    "anya-network",
    "anya-ai",
    "anya-cli"
]

[dependencies]
tokio = { version = "1.28", features = ["full"] }
slog = "2.7"
slog-term = "2.9"
config = "0.11"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libp2p = "0.51"
ipfs-api = "0.17"
yew = "0.20"
clap = { version = "4.3", features = ["derive"] }
bitcoin = "0.30"
bitcoincore-rpc = "0.16"
lightning = "0.0.116"
lightning-invoice = "0.24"
rust-dlc = "0.4"
clarity-repl = "1.0"
stacks-rpc-client = "1.0"
ndarray = "0.15"
chrono = "0.4"
ta = "0.5"
statrs = "0.16"
linfa = "0.6"
linfa-linear = "0.6"
ring = "0.16"
bitcoin = { version = "0.30", features = ["rand"] }

[dev-dependencies]
criterion = "0.5"
mockall = "0.11"
proptest = "1.0"

[[bench]]
name = "core_benchmarks"
harness = false

[features]
default = ["std"]
std = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
