[package]
name = "anya-core"
version = "1.0.0-rc1"
edition = "2021"
authors = ["Anya Development Team"]
description = "Anya Core Library for Bitcoin Development Framework"
license = "MIT"

[dependencies]
anyhow = "1.0"
bitcoin = "0.29"
chrono = "0.4"
clap = { version = "4.0", features = ["derive"] }
jsonrpc = "0.13"
log = "0.4"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.20", features = ["full"] }
tracing = "0.1"
url = "2.3"

[dev-dependencies]
tempfile = "3.3"
mockall = "0.11"
test-case = "2.2"

[features]
default = []
bitcoin_integration = []

[lib]
name = "anya_core"
path = "src/lib.rs"

[[bin]]
name = "anya-core"
path = "src/bin/anya_installer.rs" 