[package]
name = "anya-core"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
bitcoin = "0.30"
bitcoin_fee_estimation = "0.1"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
ndarray = "0.15"
ndarray-stats = "0.5"
linfa = "0.6"
linfa-linear = "0.6"
rand = "0.8"

# ... (other dependencies)
