[package]
name = "anya-core"
version = "0.2.0"
edition = "2021"
authors = ["Anya Core Contributors"]
description = "A decentralized AI assistant framework (Open Source Edition)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/anya-core/anya-core"

[workspace]
members = [
    "anya-core",
    "anya-network",
    "anya-ai",
    "anya-cli"
]

[dependencies]
tokio = { version = "1.28", features = ["full"] }
libp2p = "0.51"
bitcoin = { version = "0.30", features = ["rand"] }
lightning = "0.0.116"
stacks-rpc-client = "1.0"
rust-dlc = "0.4"
clarity-repl = "1.0"
yew = "0.20"
bulletproofs = "4.0"
slog = "2.7"
slog-term = "2.9"
config = "0.13"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
did-key = "0.1"
verifiable-credentials = "0.1"
wasmer = "2.3"
openfl = "0.1"
ndarray = "0.15"
bitcoincore-rpc = "0.16"

# New dependencies
ipfs-api = "0.17"
orbit-db = "0.1"
seal = "4.1"
mp-spdz = "0.1"
rust-bert = "0.20"

[features]
default = ["std"]
std = []
enterprise = ["advanced_analytics", "high_volume_trading"]
advanced_analytics = []
high_volume_trading = []

[dev-dependencies]
criterion = "0.5"
mockall = "0.11"
proptest = "1.0"

[[bench]]
name = "core_benchmarks"
harness = false
