[package]
name = "anya"
version = "0.1.0"
edition = "2021"
authors = ["botshelomokoka@gmail.com"]
description = "A Bitcoin, Taproot Asset and AI-enabled wallet with ZK capabilities, project setup, and setup checking"
license = "MIT"

[dependencies]
anyhow = "1.0.69"
ark-bls12-381 = "0.3.0"
ark-ec = "0.3.0"
ark-ff = "0.3.0"
ark-groth16 = "0.3.0"
ark-serialize = "0.3.0"
ark-snark = "0.3.0"
bech32 = "0.9.1"
bellman = "0.13.1"
bitcoin = { version = "0.29.2", features = ["rand"] }
bitcoincore-rpc = "0.16.0"
blake2 = "0.10.6"
clarity-repl = "0.3.1"
dotenv = "0.15.0"
env_logger = "0.10.0"
fs_extra = "1.3.0"
hex = "0.4.3"
libp2p = { version = "0.50.0", features = ["tcp-tokio", "mdns"] }
libp2p-kad = "0.42.1"
log = "0.4.17"
pairing = "0.22.0"
rand = "0.8.5"
reqwest = { version = "0.11.14", features = ["json"] }
rust-base58 = "0.0.4"
rust-bech32 = "0.9.1"
rust-bitcoin = "0.29.2"
rust-bip39 = "1.0.0"
rust-crypto = "0.2.36"
rust-dlc = "0.1.0"
rust-lightning = "0.0.115"
rust-miniscript = "9.0.0"
rust-secp256k1 = { version = "0.24.0", features = ["rand-std"] }
secp256k1 = { version = "0.24.0", features = ["rand-std"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
sha2 = "0.10.6"
stacks-common = "0.1.0"
stacks-transactions = "0.1.0"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1.37"
web5 = "0.1.0"
web5-api = "0.1.0"
web5-credentials = "0.1.0"
winterfell = "0.6.0"

# Add these new dependencies
pyo3 = { version = "0.18.3", features = ["extension-module"] }
python3-sys = "0.7.1"

[dependencies]
egui = "0.21.0"  # Use the latest version available

[build-dependencies]
pyo3-build-config = "0.18.3"

[dev-dependencies]
mockall = "0.11.3"
tokio-test = "0.4.2"

[dependencies]
yew = "0.19"
yew-hooks = "0.1"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
i18n-embed = "0.13"
i18n-embed-fl = "0.6"
