[advisories]
# Ignore specific advisories with justification
ignore = [
    # Temporary ignore RSA timing attack until alternative is implemented
    # TODO: Replace rsa crate with ring or other constant-time implementation
    { id = "RUSTSEC-2023-0071", reason = "RSA timing attack - tracking issue for migration to ring crate" }
]

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Zlib",
    "CC0-1.0",
    "MITNFA",
    "Unicode-3.0",
    "CDLA-Permissive-2.0"  # Community Data License Agreement - permissive and MIT-compatible
]
# Confidence threshold for license detection (0.8-1.0 recommended)
confidence-threshold = 0.95
exceptions = []

# License clarifications for crates with complex licensing
[[licenses.clarify]]
crate = "ring"
# ring uses a combination of licenses but is generally permissive
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0x1f628c53 }
]

[bans]
# Strict duplicate version detection
multiple-versions = "deny"
# Deny wildcard version specifications
wildcards = "deny"
# Graph highlighting for duplicate analysis
highlight = "all"
skip-tree = []

# [AIR-3][AIS-3][BPC-3][RES-3] Allow specific duplicate versions with justification
skip = [
    # Bitcoin ecosystem version conflicts - BIP39 wallet vs main bitcoin crate
    { crate = "bitcoin-internals", reason = "Version conflicts between bip39 v2.2.0 and bitcoin v0.32.6" },
    { crate = "bitcoin_hashes", reason = "Version conflicts between bip39 v2.2.0 and bitcoin v0.32.6" },
    { crate = "hex-conservative", reason = "Version conflicts between bip39 v2.2.0 and bitcoin v0.32.6" },
    
    # Build system version conflicts - transitive from librocksdb-sys
    { crate = "bindgen", reason = "Version conflicts in RocksDB build dependencies" },
    { crate = "itertools", reason = "Version conflicts between criterion and bindgen" },
    { crate = "rustc-hash", reason = "Version conflicts in bindgen dependencies" },
    
    # Crypto and random number generation conflicts
    { crate = "getrandom", reason = "Version conflicts between ring/crypto dependencies and newer crates" },
    { crate = "wasi", reason = "Version conflicts in getrandom dependency chain (0.11.1 vs 0.14.2)" },
    
    # HTTP and networking version conflicts
    { crate = "base64", reason = "Version conflicts between jsonrpc, bitcoin, and modern HTTP crates" },
    { crate = "rustls", reason = "Version conflicts between hickory-resolver and ureq" },
    { crate = "rustls-webpki", reason = "Version conflicts between rustls versions" },
    
    # General utility crate conflicts
    { crate = "hashbrown", reason = "Version conflicts between dashmap and indexmap" },
    { crate = "socket2", reason = "Version conflicts between tokio and hyper-util" },
    { crate = "regex-automata", reason = "Version conflicts between tracing-subscriber and main regex" },
    { crate = "regex-syntax", reason = "Version conflicts in regex dependency chain" },
    
    # Windows system dependencies - build-time only, multiple versions acceptable
    { crate = "windows-sys", reason = "Multiple versions from different Windows API generations (0.48-0.60)" },
    { crate = "windows-targets", reason = "Windows build targets - multiple versions acceptable" },
    { crate = "windows_aarch64_gnullvm", reason = "Windows ARM64 GNU build targets" },
    { crate = "windows_aarch64_msvc", reason = "Windows ARM64 MSVC build targets" },
    { crate = "windows_i686_gnu", reason = "Windows i686 GNU build targets" },
    { crate = "windows_i686_gnullvm", reason = "Windows i686 GNU build targets" },
    { crate = "windows_i686_msvc", reason = "Windows i686 MSVC build dependencies - multiple versions from different deps" },
    { crate = "windows_x86_64_gnu", reason = "Windows x64 GNU build dependencies - multiple versions from different deps" },
    { crate = "windows_x86_64_gnullvm", reason = "Windows x64 GNU build dependencies - multiple versions from different deps" },
    { crate = "windows_x86_64_msvc", reason = "Windows x64 MSVC build dependencies - multiple versions from different deps" }
]

# Deny problematic crates with specific security or compatibility issues
deny = [
    # Crates with known security vulnerabilities
    { crate = "openssl@<0.10.64", reason = "Multiple known security vulnerabilities in older versions" },
    { crate = "chrono@<0.4.26", reason = "RUSTSEC-2020-0071: Potential segfault in localtime_r" },
    { crate = "time@<0.3.36", reason = "RUSTSEC-2020-0071: Potential segfault in time crate" },
    
    # Problematic crypto implementations
    { crate = "sha1@<0.10.6", reason = "Weak cryptographic hash - use SHA-2 or SHA-3 family instead" },
    { crate = "md5", reason = "Cryptographically broken - use stronger hash functions" },
    
    # Unmaintained or problematic crates
    { crate = "yanked-crate", reason = "Example of yanked crate detection" }
]

[sources]
# Strict source control - only allow crates.io for now
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# Note: web5-rs git dependency removed - currently not in use
# allow-git = ["https://github.com/TBD54566975/web5-rs"]
allow-git = []
