


[advisories]
ignore = []
unmaintained = "deny"
yanked = "deny"


[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
confidence-threshold = 0.95
exceptions = []


[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
skip = []
skip-tree = []


[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
