# Site Information
site_name: Anya Core
site_url: https://docs.anya.org/
site_Author: Bo_theBig
site_description: |
  Anya Core - Enterprise-grade Bitcoin infrastructure for the next generation of financial applications.
  [AIR-3][AIS-3][BPC-3][RES-3]

# Repository
repo_url: https://github.com/anya-org/anya-core
repo_name: anya-org/anya-core
edit_uri: edit/main/docs/

# Copyright
copyright: |
  Copyright &copy; 2025 Anya Foundation

# Theme Configuration
theme:
  name: mkdocs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.action.edit
    - content.action.view

# Markdown Extensions
markdown_extensions:
  # No pymdownx extensions (removed for compatibility)
  - toc:
      permalink: true
      toc_depth: 3

# Plugins
plugins:
  - search

# Build Configuration
docs_dir: docs
site_dir: site
strict: false
use_directory_urls: true

# Extra Context
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  # logo: assets/logo.svg  # Uncomment if file exists
  # favicon: assets/favicon.ico  # Uncomment if file exists
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/Anya-org/Anya-core
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/anya-core
  #   - icon: fontawesome/brands/discord
  #     link: https://discord.gg/anya-core
