#!/bin/bash
# Script to rebuild the development container

echo "=== Rebuilding Anya Core Development Container ==="
echo ""
echo "This script will help you rebuild the development container."
echo "Please follow these steps:"
echo ""
echo "1. Open the VS Code Command Palette (F1 or Ctrl+Shift+P)"
echo "2. Type 'Dev Containers: Rebuild Container'"
echo "3. Press Enter"
echo ""
echo "After the container rebuilds, run './init-dev-container.sh' to initialize the development environment"
echo ""
echo "=== Changes Pushed to Branch ==="
echo ""
echo "After making your changes, commit them using 'git commit -m \"<commit message>\"' and push them to the 'feature/enhanced-dev-container' branch using 'git push origin feature/enhanced-dev-container'."
echo "Once pushed, create a pull request on GitHub using this link:"
echo "https://github.com/Anya-org/Anya-core/pull/new/feature/enhanced-dev-container"
echo ""
echo "Pull Request Details:"
echo "- Title: Enhanced dev container setup with complete Rust, Bitcoin, and ML tooling support"
echo "- Description: Add details about the changes made to the dev container setup"
echo ""
echo "After the PR is approved and merged, the changes will be available in the main branch."
