[package]
name = "anya-privacy"
version = "1.0.0"
edition = "2021"
authors.workspace = true
description = "Privacy enhancements including BIP-353 Silent Payments for Anya Core"
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
# Bitcoin dependencies
bitcoin = { version = "0.32.0" }
secp256k1 = { workspace = true }
bdk = { workspace = true, optional = true }

# Async runtime
tokio = { workspace = true, optional = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Logging & metrics
tracing = { workspace = true }
metrics = { workspace = true }

# Security
sha2 = { workspace = true }
zeroize = { workspace = true }
chacha20poly1305 = { workspace = true }
aes-gcm = { workspace = true }

[features]
default = ["bdk-wallet", "async"]
bdk-wallet = ["dep:bdk"]
async = ["dep:tokio"]
hardware-security = []

[dev-dependencies]
tempfile = { workspace = true }
test-log = { workspace = true } 
