[target.'cfg(mobile)'.dependencies]
anya-mobile = { git = "https://github.com/anya-org/anya-mobile" }
secp256k1 = { workspace = true, features = ["mobile", "bip340", "bip341"] }
bitcoin = { workspace = true, features = ["mobile", "taproot", "bip341"] }

[features]
default = ["bip340", "bip341", "bip342"]
bip340 = ["secp256k1/bip340"]
bip341 = ["bitcoin/bip341", "secp256k1/bip341"]
bip342 = ["bitcoin/bip342", "secp256k1/bip342"] 