# [AIR-3][AIS-3][BPC-3][RES-3]
# ===================================================================
# ALERTMANAGER CONFIGURATION
# Part of the Anya Core Monitoring Stack
# Version: 2.6.0
# Last Updated: 2025-05-21
#
# Description:
#   This configuration file defines alert routing, grouping, and notification
#   settings for the Alertmanager service.
#
# Security:
#   - Uses environment variables for sensitive data
#   - Enforces TLS for all email communications
#   - Implements rate limiting to prevent notification storms
#
# AI Labeling:
#   [AIR-3] - Automated alert routing and management
#   [AIS-3] - Secure configuration with environment variables
#   [BPC-3] - Follows Bitcoin node monitoring best practices
#   [RES-3] - Resilient alert delivery with retries
# ===================================================================

global:
  # Time after which an alert is declared resolved if it has not been updated
  resolve_timeout: 5m
  
  # SMTP server configuration for email alerts
  smtp_smarthost: 'smtp.gmail.com:587'  # Gmail SMTP server with STARTTLS
  smtp_from: '${ALERT_EMAIL_FROM:-botshelomokoka@gmail.com}'
  smtp_auth_username: '${ALERT_EMAIL_USER:-botshelomokoka@gmail.com}'
  smtp_auth_password: '${ALERT_EMAIL_PASSWORD}'
  smtp_require_tls: true  # Enforce TLS encryption
  smtp_hello: 'gmail.com'  # HELO/EHLO domain
  
  # Rate limiting for notifications
  http_config:
    follow_redirects: true
    enable_http2: true
    tls_config:
      insecure_skip_verify: false  # Always verify TLS certificates
  
  # Default template files
  templates:
    - '/etc/alertmanager/templates/*.tmpl'

route:
  # Group alerts by alertname and severity
  group_by: ['alertname', 'severity']
  # Initial delay before sending first notification for a new group
  group_wait: 30s
  # Time between sending notifications about new groups
  group_interval: 5m
  # Time between sending notifications if new alerts are still firing
  repeat_interval: 3h
  # Default receiver
  receiver: 'slack'
  # Child routes for specific alert types
  routes:
    # Suppress Watchdog alerts
    - match:
        alertname: Watchdog
      receiver: 'null'
    # Critical alerts
    - match:
        severity: 'critical'
      receiver: 'slack'
      continue: true
    # Warning alerts
    - match:
        severity: 'warning'
      receiver: 'slack'

receivers:
  # Null receiver for suppressed alerts
  - name: 'null'
  
  # Slack receiver
  - name: 'slack'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts'
        send_resolved: true
        title: '{{ template "slack.anya.title" . }}'
        text: '{{ template "slack.anya.text" . }}'
        color: '{{ if eq .Status "firing" }}{{ if eq .CommonLabels.severity "critical" }}danger{{ else }}warning{{ end }}{{ else }}good{{ end }}'

  # Email receiver
  - name: 'email'
    email_configs:
      - to: 'botshelomokoka@gmail.com'
        send_resolved: true
        headers:
          subject: '[ANYA-CORE {{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}'
        html: '{{ template "email.anya.html" . }}'

  # PagerDuty receiver
  - name: 'pagerduty'
    pagerduty_configs:
      - service_key: '${PAGERDUTY_KEY}'
        description: '{{ .CommonAnnotations.summary }}'
        details:
          firing: '{{ .CommonAnnotations.description }}'
          severity: '{{ .CommonLabels.severity }}'
          status: '{{ .Status }}'

# Templates for alert messages
templates:
  - '/etc/alertmanager/templates/*.tmpl'
