[package]
name = "security"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { workspace = true }
secp256k1 = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

[features]
hsm = []
