name: Sync Enterprise Updates

on:
  push:
    branches: [ main ]
    paths:
      - 'anya-core/**'
      - '.github/workflows/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-enterprise:
    runs-on: ubuntu-latest
    if: github.repository == 'anya-org/anya-core'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Git Config
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          
      - name: Sync Enterprise Module
        env:
          ENTERPRISE_TOKEN: ${{ secrets.ENTERPRISE_REPO_TOKEN }}
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          
          if [ -d "anya-enterprise" ]; then
            cd anya-enterprise
            echo "Fetching latest changes from enterprise repository..."
            git fetch origin main || { echo "::error::Failed to fetch from origin"; exit 1; }
            
            echo "Merging changes from main branch..."
            git merge origin/main --ff-only || { echo "::error::Fast-forward merge failed. Please resolve conflicts manually"; exit 1; }
            
            echo "Pushing changes to origin..."
            git push origin main || { echo "::error::Failed to push to origin"; exit 1; }
          else
            echo "anya-enterprise directory not found"
            exit 1
          fi

