[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.1", features = ["full", "macros"] }
hex = "0.4"
rand = "0.8"
anya-core = { path = "../anya-core" }

[[bin]]
name = "anya"
path = "src/main.rs"
