[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
rand = "0.8"
tokio = { version = "1", features = ["full"] }
hex = "0.4"
url = "=2.2.2"
bitcoin = "0.29.2"
secp256k1 = "0.24.0"
tokio = { version = "1.28.1", features = ["full"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
anyhow = "1.0.70"
thiserror = "1.0.40"
log = "0.4.17"
reqwest = { version = "0.11.11", default-features = false, features = ["json", "rustls-tls"] }
rand = "0.8"

[lib]
name = "core"
path = "src/lib.rs"

[dev-dependencies]
tokio = { version = "1.28.1", features = ["full", "test-util", "macros"] }
rand = "0.8.5"
