[package]
name = "anya-core"
version.workspace = true
edition = "2021"
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
bitcoin.workspace = true
secp256k1.workspace = true
serde.workspace = true
libp2p = { workspace = true, features = ["tcp", "websocket", "noise", "yamux"] }
tokio = { workspace = true, features = ["full"] }

# Cryptographic primitives
k256 = { version = "0.13.3", features = [
    "ecdsa",
    "sha256",
    "std"
] }
sha2 = "0.10.8"
hmac = "0.12.1"

# Security auditing
cargo-audit = { version = "0.18.3", optional = true }

# Update Web5 dependencies with security features
# web5 = { version = "0.5.1", features = [
#     "bip174",
#     "bip341",
#     "bip370",
#     "did-rotation",
#     "vc-revocation",
#     "silent-leaf"
# ], default-features = false }

# Add SGX implementation
sgx_urts = { version = "1.1.1", optional = true }

# Change yubihsm to optional
yubihsm = { version = "0.41.0", optional = true }

[dev-dependencies]
# Commenting out due to non-existent git commit
# bip-check = { git = "https://github.com/bitcoin/bips", rev = "7c4b4c1d91b7d3dc6d7862ad5a8c1472332e6d84" }
# web5-test-vectors = "0.2.0"

[features]
default = ["audit"]
audit = ["cargo-audit"]
hardware = ["hsm", "sgx_urts"]
hsm = ["yubihsm"]
chaos = [
    "tokio/full"
]
sgx = ["sgx_urts"]
mobile = ["bitcoin/serde", "secp256k1/global-context"]

# REMOVED CONFLICTING WORKSPACE SECTION

