#!/bin/bash
# [AIR-3][AIS-3][BPC-3][DAO-3]
# Business Agent Deployment Script
# Auto-generated by DAO Agent Automation System

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}Starting DAO Business Agent Deployment${NC}"

# Deploy smart contracts (if clarinet is available)
if command -v clarinet &> /dev/null; then
    echo -e "${YELLOW}Deploying smart contracts...${NC}"
    clarinet contracts deploy
else
    echo -e "${YELLOW}Clarinet not available, skipping contract deployment${NC}"
fi

# Run integration tests
echo -e "${YELLOW}Running integration tests...${NC}"
if command -v cargo &> /dev/null; then
    cargo test --test integration_tests || echo "Some tests may require full environment setup"
fi

echo -e "${GREEN}Business Agent deployment completed!${NC}"
