[package]
name = "anya-enterprise"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
rand = "0.8"
tokio = { version = "1", features = ["full"] }
rand = "0.8"
hex = "0.4"

# Target specification added automatically
[lib]
name = "anya_enterprise"
path = "src/lib.rs"

