# Anya Monitoring Configuration

monitoring:
  health_check:
    interval: 300  # seconds
    log_file: "../logs/ops_health.log"
    metrics_file: "../metrics/system_metrics.json"
    thresholds:
      cpu: 90
      memory: 90
      disk: 90

  prometheus:
    port: 9090
    metrics_path: "/metrics"
    scrape_interval: 60  # seconds

  alerts:
    enabled: true
    channels:
      - type: "log"
        path: "../logs/alerts.log"
      - type: "prometheus"
        endpoint: "http://localhost:9090/metrics"

  log_retention:
    enabled: true
    max_age_days: 30
    max_size_mb: 500
    min_free_space_percent: 20
    requirements:
      - type: "backup_exists"
        path: "../backups/logs"
      - type: "metrics_exported"
        status: true
      - type: "min_retention_period"
        days: 7

  log_rotation:
    enabled: true
    max_files: 5
    compress: true
    size_trigger: "100M"

  log_backup:
    enabled: true
    schedule: "0 0 * * *"  # Daily at midnight
    retention:
      daily: 7
      weekly: 4
      monthly: 3

services:
  - name: "web5_service"
    type: "core"
    healthcheck: "/health"
  - name: "bitcoin_service"
    type: "core"
    healthcheck: "/health"
  - name: "search_service"
    type: "core"
    healthcheck: "/health"

logging:
  level: "info"
  format: "json"
  output:
    - type: "file"
      path: "../logs/ops_health.log"
    - type: "stdout"
