[package]
name = "anya-core-lib"
version.workspace = true
edition.workspace = true
description = "Core implementation for Anya Bitcoin Framework"
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# Use workspace dependencies
bitcoin.workspace = true
bdk.workspace = true
tokio.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true

[features]
default = ["taproot", "psbt-v2"]
taproot = ["bitcoin/taproot"]
psbt-v2 = ["bdk/psbt-v2"]
