[package]
name = "anya-core-core"
version.workspace = true
edition.workspace = true
description = "Core implementation for Anya Bitcoin Development Framework"
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# Bitcoin dependencies with correct features for BIP-342 support
bitcoin = { version = "0.32.0", features = ["std", "serde", "rand", "bitcoinconsensus"] }
secp256k1 = { version = "0.28.1", features = ["std", "serde", "rand"] }

# Tokio runtime
tokio = { workspace = true }
futures = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Logging
log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Async traits
async-trait = { workspace = true }

[features]
default = ["std"]
std = []
dlc = []  # Discrete Log Contracts
psbt-v2 = []
