[package]
name = "anya-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.1", features = ["full", "macros"] }
hex = "0.4"
rand = "0.8"
serde_json = "1.0.96"
bitcoin = "0.29.2"
core = { path = "../core" }
log = "0.4.17"
env_logger = "0.10.0"
reqwest = { version = "0.11.11", default-features = false, features = ["json", "rustls-tls"] }

[lib]
name = "anya_core"
path = "src/lib.rs"

[[bin]]
name = "anya-core"
path = "src/main.rs"
