[workspace]
members = [
    "anya-core-pkg",
    "dependencies/anya-bitcoin",
    "dependencies/anya-web5"
]
resolver = "2"
exclude = [
    "target",
    "scripts",
    "docs"
]
required-features = ["bip341"]

[workspace.metadata.compliance]
features = ["bip341", "secp256k1/std"]
audit = "2025-02-24"

[workspace.metadata.compliance.security]
relro = "full"
now = true

[workspace.dependencies]
# Unified Bitcoin Development Framework v2.5 dependencies
bitcoin = { version = "0.32.0", features = [
    "std", 
    "bip341", 
    "serde", 
    "rand", 
    "bitcoinconsensus"
]}
secp256k1 = { version = "0.28.1", features = ["std", "serde", "bitcoin_hashes", "rand"] }
hex = { version = "0.4.3", features = ["serde", "std"] }
hex-literal = { version = "0.4.1", features = ["serde"] }
rand = { version = "0.8.5", features = ["std_rng", "getrandom"] }
anyhow = { version = "1.0.75", features = ["std"] }
thiserror = "1.0.50"
log = "0.4.20"
serde = { version = "1.0", features = ["derive", "std"] }
serde_json = "1.0.96"
tokio = { version = "1.32.0", features = ["full", "rt-multi-thread", "parking_lot", "macros", "signal"] }

[workspace.package]
version = "0.1.0"
authors = ["Anya Maintainers"]
description = "Bitcoin Layer 4 Protocol Implementation"
license = "Apache-2.0"
repository = "https://github.com/anya-org/anya-core"
rust-version = "1.70"
edition = "2021"

[workspace.lints.rust]
unsafe_code = "forbid"  # Framework security requirement
