[package]
name = "anya-core"
version = "0.2.0"
edition = "2021"
authors = ["Anya Core Contributors"]
description = "A decentralized AI assistant framework (Open Source Edition)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/anya-core/anya-core"

[workspace]
members = [
    "anya-core",
    "anya-network",
    "anya-ai",
    "anya-cli"
]

[dependencies]
# Async runtime and networking
tokio = { version = "*", features = ["full", "test-util"] }
libp2p = "*"

# Blockchain and cryptocurrencies
bitcoin = { version = "*", features = ["rand"] }
lightning = "*"
stacks-rpc-client = "*"
rust-dlc = "=0"
clarity-repl = "*"
bitcoincore-rpc = "*"

# Web and UI
yew = "*"

# Cryptography and security
bulletproofs = "*"
did-key = "*"
verifiable-credentials = "*"

# Logging and configuration
slog = "*"
slog-term = "*"
config = "*"
log = "*"
env_logger = "*"

# Serialization and error handling
serde = { version = "*", features = ["derive"] }
serde_json = "*"
thiserror = "*"

# WebAssembly and AI
wasmer = "*"
openfl = "*"
ndarray = "*"
rust-bert = "*"

# Distributed systems and storage
ipfs-api = "*"
orbit-db = "*"

# Cryptographic protocols
seal = "*"
mp-spdz = "*"

# DLC library support
dlc-btc-lib = { git = "https://github.com/DLC-link/dlc-btc-lib" }

[dev-dependencies]
criterion = "*"
tokio-test = "*"
mockall = "*"
proptest = "*"
tempfile = "*"

[build-dependencies]
neon-build = "*"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["std"]
std = []
enterprise = ["advanced_analytics", "high_volume_trading"]
advanced_analytics = []
high_volume_trading = []

[[bench]]
name = "core_benchmarks"
harness = false
