[package]
name = "anya-fix-scripts"
version = "0.1.0"
edition = "2021"
description = "Cross-platform fix scripts for Anya Core"
authors = ["Anya Core Team"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
regex = "1.10"
walkdir = "2.5"
anyhow = "1.0"
colored = "2.1" 