title: Anya Documentation
description: Enterprise-grade Bitcoin Infrastructure Platform
theme: jekyll-theme-minimal

# GitHub Pages settings
baseurl: "/anya-core"
url: "https://botshelomokoka.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# GitHub metadata
github:
  is_project_page: true
  repository_url: https://github.com/botshelomokoka/anya-core
  repository_name: anya-core
  owner_url: https://github.com/botshelomokoka
  owner_name: Botshelo Mokoka

# Navigation
nav_links:
  - title: Getting Started
    url: /getting-started/
  - title: Installation
    url: /installation/cross-platform/
  - title: API Reference
    url: /api/
  - title: Architecture
    url: /architecture/
  - title: Security
    url: /security/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .git/
  - .github/
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - CNAME
