[package]
name = "anya-bitcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }

# Target specification added automatically
[lib]
name = "anya_bitcoin"
path = "src/lib.rs"

