[package]
name = "anya-core-protocol-adapters"
version = "2.5.0"
edition = "2021"
description = "Protocol adapters for Anya Core"
authors = ["Anya Team <team@anya.dev>"]
license = "MIT"

[dependencies]
# Core dependencies
anya-core-lib = { path = "../core" }
log = "0.4"
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Bitcoin dependencies
bitcoin = "0.29"

[features]
default = []
