name: Anya Core Validation
on: [push, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Anya Core Validation
        run: |
          cargo anya-validate \
            --features bip-341,bip-370 \
            --optimization 3 \
            --circuit-version 2.1
          
      - name: Model Checksum Verification
        uses: anya-core/model-integrity@v2
        with:
          expected_hash: ${{ secrets.MODEL_HASH }} 