# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Bandit is a security linter designed to find common security issues in Python code.
# This action will run Bandit on your codebase.
# The results of the scan will be found under the Security tab of your repository.

# https://github.com/marketplace/actions/bandit-scan is ISC licensed, by abirismyname
# https://pypi.org/project/bandit/ is Apache v2.0 licensed, by PyCQA

name: Bandit
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '38 3 * * 3'

jobs:
  bandit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with:
          # exit with 0, even with results found
          exit_zero: true
          # Github token of the repository (automatically created by Github)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # File or directory to run bandit on
          path: .
          # Report only issues of a given severity level or higher. Can be LOW, MEDIUM or HIGH.
          level: LOW
          # Report only issues of a given confidence level or higher. Can be LOW, MEDIUM or HIGH.
          confidence: LOW
          # comma-separated list of paths (glob patterns supported) to exclude from scan
          excluded_paths: .svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg
          # comma-separated list of test IDs to skip
          skips: B101,B102
          # path to a .bandit file that supplies command line arguments
          ini_path: .bandit
