name: Chaos Engineering

on:
  schedule:
    - cron: '0 3 * * 6' # Weekly Saturday 3AM
  workflow_dispatch:

jobs:
  bitcoin-network-failure:
    runs-on: ubuntu-latest
    steps:
    - name: Simulate Bitcoin Core crash
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --bin chaos-engine -- network partition --duration 300 --protocol bitcoin

    - name: Validate failover
      run: |
        anya-cli check node-status --expected backup-active
        anya-cli check transactions --window 5m --threshold 95

  hardware-failure:
    runs-on: ubuntu-latest
    steps:
    - name: Simulate HSM failure
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --bin chaos-engine -- hardware failure --component hsm

    - name: Validate key rotation
      run: |
        anya-cli check key-rotation --threshold 90%

  double-spend-attack:
    runs-on: ubuntu-latest
    steps:
    - name: Simulate double spend
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --bin chaos-engine -- attack double-spend --count 100

    - name: Validate detection
      run: |
        anyya-cli check security-events --type double-spend --min 95

  mempool-flood:
    runs-on: ubuntu-latest
    steps:
    - name: Flood mempool
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --bin chaos-engine -- stress mempool --tps 1000 --duration 600

    - name: Check propagation
      run: |
        anyya-cli monitor propagation --threshold 90%

  network-chaos:
    runs-on: ubuntu-latest
    steps:
    - name: Simulate network partitions
      uses: chaostoolkit/chaostoolkit@v1
      with:
        experiment: |
          {
            "title": "Network Partition Test",
            "method": [
              {
                "type": "action",
                "name": "block-rpc-traffic",
                "provider": {
                  "type": "python",
                  "module": "chaosbitcoin.actions",
                  "func": "block_port",
                  "arguments": {
                    "port": 8332,
                    "duration": 300
                  }
                }
              }
            ],
            "rollbacks": [
              {
                "type": "action",
                "name": "restore-rpc-traffic",
                "provider": {
                  "type": "python",
                  "module": "chaosbitcoin.actions",
                  "func": "unblock_port",
                  "arguments": {
                    "port": 8332
                  }
                }
              }
            ]
          }

  resource-exhaustion:
    runs-on: ubuntu-latest
    steps:
    - name: CPU stress test
      uses: chaostoolkit/chaostoolkit@v1
      with:
        experiment: |
          {
            "title": "CPU Exhaustion Test",
            "method": [
              {
                "type": "action",
                "name": "stress-cpu",
                "provider": {
                  "type": "process",
                  "path": "stress-ng",
                  "arguments": "--cpu 0 --timeout 300"
                }
              }
            ]
          }

  failover-test:
    runs-on: ubuntu-latest
    steps:
    - name: Node failover simulation
      uses: chaostoolkit/chaostoolkit@v1
      with:
        experiment: |
          {
            "title": "Node Failover Test",
            "method": [
              {
                "type": "action",
                "name": "stop-bitcoind",
                "provider": {
                  "type": "process",
                  "path": "systemctl",
                  "arguments": "stop bitcoind"
                }
              },
              {
                "type": "probe",
                "name": "check-failover",
                "provider": {
                  "type": "http",
                  "url": "http://localhost:8332",
                  "timeout": 5
                },
                "tolerance": 500
              }
            ]
          } 