name: "Docs Validation"

on:
  push:
    branches:
      - main
      - 'release/*'
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *'

jobs:
  html-proofer:
    name: "Validate Generated Docs"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'
          bundler-cache: true

      - name: Install JS (Node)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Jekyll site
        run: |
          gem install jekyll html-proofer
          bundle exec jekyll build --source docs --destination _site --strict

      - name: Validate HTML links
        run: |
          htmlproofer ./_site --assume-extension --check-html --url-ignore "#/"
