name: "Documentation Health Check"

on:
  push:
    branches:
      - main
      - 'release/*'
      - 'branch-management-*'
    paths:
      - '**/*.md'
      - 'docs/**'
      - 'mkdocs.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch: {}
  schedule:
    - cron: '0 1 * * 1'  # Weekly on Monday at 1 AM

jobs:
  link-check:
    name: "Check Documentation Links"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for accurate timestamps

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install markdown-link-check mkdocs mkdocs-material

      - name: Run link validation
        run: |
          chmod +x scripts/validate_links_ci.sh
          ./scripts/validate_links_ci.sh

      - name: Upload link report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: link-campaign-report
          path: link_campaign_report.md
          retention-days: 14

  build-docs:
    name: "Build Documentation"
    runs-on: ubuntu-latest
    needs: link-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build documentation
        run: |
          mkdocs build --strict

      - name: Upload documentation build
        uses: actions/upload-artifact@v3
        with:
          name: documentation-build
          path: site/
          retention-days: 7

  markdown-lint:
    name: "Markdown Linting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdownlint
        run: |
          npm install -g markdownlint-cli

      - name: Run markdownlint
        run: |
          markdownlint '**/*.md' --ignore node_modules
