
# ✨ chore(docs): switch to JamesIves deploy action for GitHub Pages [AIR-3][AIS-3][BPC-3][RES-3]
name: Deploy to GitHub Pages
on:
  push:
    branches: [main, release/*]
    paths:
      - 'docs/**'
      - '.github/workflows/gh-pages.yml'
      - 'mkdocs.yml'
  workflow_dispatch:


permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-docs.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
          pip install mkdocs-include-markdown-plugin

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Check for broken links
        run: mkdocs build --no-directory-urls

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
          clean: true
          single-commit: true
