name: Mobile Cross-Validation
on: [push, pull_request]

jobs:
  mobile-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
      
      - name: Clone external mobile
        run: git clone https://github.com/anya-org/anya-mobile
      
      - name: Run cross-validation
        run: |
          cargo install --path ./tools/mobile-checker
          mobile-checker \
            --local-path ./mobile \
            --external-path ./anya-mobile \
            --report compliance.json \
            --fail-on critical
        env:
          RUST_BACKTRACE: 1
      
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: mobile-compliance
          path: compliance.json 