name: Cross-Repo Compliance
on: [push, workflow_dispatch]

jobs:
  repo-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'anya-org/anya-core'
          path: anya-core
      
      - name: Analyze Bitcoin Repo
        run: |
          cd anya-core/dependencies/anya-bitcoin
          cargo anya-compliance --report bitcoin.json
      
      - name: Analyze Mobile Repo
        run: |
          cd anya-core/dependencies/anya-mobile
          cargo anya-compliance --report mobile.json 