- name: Protocol Adherence Check
  run: |
    cargo test --features protocol_adherence
    ./scripts/validate_docs.ps1 -ProtocolCheck
  env:
    RUSTFLAGS: '-D warnings'

- name: Security Audit
  run: |
    cargo geiger --all-features
    cargo audit 

- name: Mobile Build
  run: |
    cd mobile
    npm install
    go mod tidy
    gomobile bind -target android -o android/bitcoin.aar ./pkg/bitcoin 