name: Security Audit

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly audits
  workflow_dispatch:

jobs:
  full-audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run security tests
      run: |
        cargo test --release --lib --bins -p anya-installer -- security::
        cargo run --bin anya-validator -- check-all --report=full

    - name: Generate compliance report
      run: |
        cargo run --bin anya-audit -- --format json > security_report.json

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: security-audit-${{ github.sha }}
        path: |
          security_report.json
          logs/audit.log

    - name: Check BIP compliance
      run: |
        cargo run --bin anya-validator -- check-compliance --bip=341,342,174,370

    - name: Fuzz testing
      uses: actions-rs/cargo@v1
      with:
        command: fuzz
        args: run --release -- -max_total_time=300 