name: Security Scanning (Combined)

on:
  push:
    branches: [ main, new-develop ]
  pull_request:
    branches: [ main, new-develop ]
  schedule:
    - cron: '0 2 * * 1' # Weekly on Mondays at 2AM
  workflow_dispatch:

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          
      - name: Run cargo audit
        run: |
          cargo install cargo-audit
          cargo audit --deny warnings
          
      - name: Run Secret Scanning
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v3
        
  code-scanning:
    name: Code Scanning
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: rust
          queries: +security-and-quality
          
      - name: Build for Analysis
        uses: github/codeql-action/autobuild@v2
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  bitcoin-security:
    name: Bitcoin Protocol Security
    runs-on: ubuntu-latest
    needs: code-scanning
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          
      - name: Run Bitcoin Security Tests
        run: |
          cargo test --package anya-security --features bitcoin -- security
          
      - name: Check BIP Compliance Security
        run: |
          cargo run --bin anya_validator -- security-check
          
      - name: Cryptographic Implementation Validation
        run: |
          cargo test --package anya-crypto -- --test-threads=1
          
  ai-label-validation:
    name: AI Label Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate AI Labels
        run: |
          cargo run --bin anya_validator -- validate-labels --strict
          
      - name: Report Issues
        if: failure()
        run: |
          cargo run --bin anya_validator -- generate-label-report --format markdown > ai-label-report.md
          
      - name: Upload Report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ai-label-validation-report
          path: ai-label-report.md 