name: Web5 Compliance Checks

on: [push, pull_request]

jobs:
  web5-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      
      - name: Run Web5 Tests
        run: |
          cargo test --package anya-core --lib -- web5::tests --test-threads=1
          cargo run --bin anya-audit -- --web5 --output compliance.json
      
      - name: Upload Compliance Report
        uses: actions/upload-artifact@v3
        with:
          name: web5-compliance-report
          path: compliance.json 