name: BDF Workspace Validation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  bdf-compliance:
    name: BDF 2.5 Compliance Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75
          override: true
      
      - uses: Swatinem/rust-cache@v2
      
      - name: Workspace Integrity Check
        run: |
          cargo bdf-check
          cargo doc --workspace --no-deps
          cargo audit --deny warnings
          cargo clippy --workspace --all-targets -- -D warnings
          cargo fmt --all -- --check
      
      - name: BIP Compliance Verification
        run: cargo test --workspace -- --test-threads=1
      
      - name: Security Audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-check:
    name: Crate Publish Validation
    needs: bdf-compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          for crate in installer cli core network; do
            cargo publish --dry-run --manifest-path $crate/Cargo.toml
          done 